services:
  - type: web
    name: fest-studio
    env: python
    region: oregon
    plan: free  # Or 'starter' for more resources
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --worker-class gthread -w 1 app:app"

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: SESSION_COOKIE_SECURE
        value: "true"
      - key: SUPABASE_URL
        fromService:
          type: external_service
          name: supabase-fest-studio
          envVarKey: SUPABASE_URL
      - key: SUPABASE_KEY
        fromService:
          type: external_service
          name: supabase-fest-studio
          envVarKey: SUPABASE_KEY
      # Optional but recommended
      - key: SECRET_KEY
        sync: false
      - key: WTF_CSRF_SECRET_KEY
        sync: false
